task-55-add service worker
wordrunners/bumble pull request #15
Opened 2022-12-13 11:13 UTC by kvitkina

Добавлен Service Worker

2022-12-13 14:13 UTC, evdoshchenko approved these changes

2022-12-15 16:05 UTC, EzhikTT commented on packages/client/src/App.tsx
> +            console.log(data)
Он несет в себе сакральный смысл в репозитории? Или забыли просто?

2022-12-15 16:06 UTC, EzhikTT requested changes

2022-12-15 16:06 UTC, EzhikTT commented on packages/client/src/App.tsx
> +            const url = `http://localhost:${__SERVER_PORT__}`
Почему полностью не вынесли в константу путь?

2022-12-15 21:57 UTC, kvitkina commented on packages/client/src/App.tsx
> +            console.log(data)
Что именно? fetchServerData? Он был при клонировании репозитория. То есть нам он не пригодится в следующих спринтах и можно удалять?

2022-12-16 19:04 UTC, merged