Task 59 game beatiful
wordrunners/bumble pull request #16
Opened 2022-12-16 14:40 UTC by evdoshchenko

### Какую задачу решаем

Task 59  – Добавьте в игру «красоты» – реализованны механики визуализации выбора сектора, выбора режима игры, добавлена функция рейтинговой игры с рандомными карточками, улучшено определение сектора, 
Task 56 – Добавьте минимум одно Web API – FullScreen
Task 61 – Reselect, Redux Thunk (или Redux-Saga) – ReduxToolkit, добавлены Slices для Лидерборода и временный gameUser, до появление полноценного User 

### Скриншоты/видяшка (если есть)
<img width="1238" alt="image" src="https://user-images.githubusercontent.com/85300875/208121611-d810d2c3-a82d-4b4f-b172-43431a074acf.png">

### TBD (если есть)

2022-12-16 15:10 UTC, Andrey-A-A approved these changes
Молодец, провел большую работу.

2022-12-16 19:08 UTC, kvitkina approved these changes

2022-12-17 12:08 UTC, evorobyevaa approved these changes

2022-12-19 08:18 UTC, EzhikTT requested changes

2022-12-19 08:18 UTC, EzhikTT commented on packages/client/src/pages/gamePage/game/components/gamePlay.tsx
> +          dispatch(setBumble(undefined))
А почему не `null` или пустую строку?

2022-12-19 20:00 UTC, merged