WRDRN-37 Добавить WEB API (кроме Canvas, Fetch).
wordrunners/bumble pull request #28
Opened 2023-01-14 02:57 UTC by pritornyi

### Какую задачу решаем
Добавил аудио-сопровождение на базе media api. 

### Скриншоты/видяшка (если есть)
![image](https://user-images.githubusercontent.com/22426386/212447758-9f23e321-71aa-41da-a6fd-d0412c3bfbc7.png)

### TBD (если есть)

2023-01-14 09:03 UTC, evdoshchenko approved these changes

2023-01-14 16:50 UTC, kvitkina approved these changes

2023-01-15 11:46 UTC, EzhikTT requested changes

2023-01-15 11:46 UTC, EzhikTT commented on packages/client/src/components/MusicPlayer/MusicPlayer.tsx
> +import BackgroundMusic from '../../assets/audio/POL-super-match-short.wav'
Почему здесь не через `@`?

2023-01-24 11:38 UTC, merged