Task 25/leaderboard api
wordrunners/bumble pull request #29
Opened 2023-01-14 17:23 UTC by kvitkina

Добавление API лидерборда

![Снимок экрана 2023-01-14 в 16 09 15](https://user-images.githubusercontent.com/63880873/212486592-1ba90607-6635-442a-aaec-ef3f540c3e6a.png)

2023-01-14 17:53 UTC, kvitkina commented
При первой загрузке иногда не подхватывается login юзера в рейтинговой игре (отображается 'Semen').  Нужно будет проверить после удаления localStorage.

2023-01-15 11:49 UTC, EzhikTT commented on packages/client/src/pages/gamePage/game/components/gamePlay.tsx
> +        // for (let i = 0; i <= ((totalPlayers + 1) * ROUNDS - 1); i++) {
Зачем закомментированный код в репозитории, если этот код в гите остался в истории?

2023-01-15 11:52 UTC, EzhikTT requested changes

2023-01-15 11:52 UTC, EzhikTT commented on packages/client/src/pages/startPage/startPage.tsx
> +import { addPlayer } from '../gamePage/game/core/gameSlice';
Здесь тоже путь через `@` не должен быть?

2023-01-15 11:52 UTC, EzhikTT commented on packages/client/src/pages/gamePage/game/components/gameOver.tsx
>  } from '../core/gameSlice'
Почему здесь пути не через `@`?

2023-01-16 06:48 UTC, merged