Task 66 Рефакторинг, доработка и формализация кода бэкэнда.
wordrunners/bumble pull request #39
Opened 2023-01-28 09:12 UTC by pritornyi

### Какую задачу решаем

Работа над рефакторингом бэкэнд-части приложения, доработка ручек.
### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-01-28 11:00 UTC, evdoshchenko commented on packages/server/src/Router/boardsRoutes.ts
> +    .get(GET_COMMENTS_ROUTE, getCommentList)
.post(GET_COMMENTS_ROUTE, getCommentList)

2023-01-28 11:00 UTC, evdoshchenko commented on packages/server/src/Router/boardsRoutes.ts
> +    .put(ADD_LIKE_ROUTE, toggleLike)
.post(ADD_LIKE_ROUTE, toggleLike)

2023-01-28 11:00 UTC, evdoshchenko commented on packages/server/src/Router/boardsRoutes.ts
> +    .get(GET_LIKES_BY_USER_ROUTE, getUserLikeList)
.post(GET_LIKES_BY_USER_ROUTE, getUserLikeList)

2023-01-28 11:02 UTC, evdoshchenko commented on packages/server/src/Router/routes.ts
> +export const GET_LIKES_BY_USER_ROUTE = `/get-user-likes`;
Тогда нужно на клиенте исправить в файле packages/client/src/store/boards/routes.ts

export const GET_LIKES_ROUTE = `/boards/get-user-likes`;

2023-01-30 10:00 UTC, EzhikTT requested changes

2023-02-01 00:22 UTC, pritornyi commented on packages/server/src/API/comment.ts
> +        user_login: userLogin,
Изначально мне не хотелось оставлять string значение для PK таблицы (тем более что оно вводится пользователем), это показалось плохой практикой. Свежим взглядом оценил ситуацию - справедливо можно избавиться от лишней колонки, убрал.

2023-02-14 00:13 UTC, merged