theme-server
wordrunners/bumble pull request #46
Opened 2023-02-01 01:38 UTC by evdoshchenko

Настроена Темизация:
* Переключение делается через «ручки» на NodeJS.
* Есть минимум две темы, которые отличаются стилями на клиенте.
* Стили переключаются мгновенно и без перезагрузки страницы.
* Для хранения тем используется база данных PostgreSQL версии 12+.
* В таблице темы привязаны к пользователю.

2023-02-01 12:31 UTC, kvitkina approved these changes

2023-02-02 07:57 UTC, kvitkina approved these changes

2023-02-03 08:04 UTC, EzhikTT commented on packages/client/src/pages/leaderboardPage/leaderboardPage.tsx
> +    // dispatch(fetchUser());
Закомментированный код не нужен в репозитории. Он и так под гитом уже

2023-02-03 08:05 UTC, EzhikTT requested changes

2023-02-03 08:05 UTC, EzhikTT commented on packages/client/src/components/Togglers/Togglers.tsx
> +  if (typeof window !== 'undefined') {
А проверять просто что он есть через приведение типов неявное `if(window)` нельзя?

2023-02-03 13:05 UTC, evdoshchenko commented on packages/client/src/components/Togglers/Togglers.tsx
> +  if (typeof window !== 'undefined') {
Эта проверка нужна для SSR. Так как там нету window, при сравнение if (window) выпадает ошибка `ReferenceError: window is not defined
`

2023-02-03 13:07 UTC, merged