Task 14, 15 Страницы регистрации и авторизации
wordrunners/bumble pull request #5
Opened 2022-11-29 15:43 UTC by evorobyevaa

Добавлена страница авторизации
![2022-11-29_18-36-26](https://user-images.githubusercontent.com/82096483/204574719-6e0cdd8d-1688-4fb0-97a8-48de54b6328b.png)
Добавлена страница регистрации
![2022-11-29_18-36-53](https://user-images.githubusercontent.com/82096483/204574752-bb7402f4-58d5-4909-919e-508fdb20cdc1.png)
Добавлена валидация форм

2022-11-29 17:13 UTC, kvitkina approved these changes
Теперь в проекте есть hook) Супер

2022-11-29 18:22 UTC, evdoshchenko approved these changes
Все ок!

2022-11-30 10:16 UTC, EzhikTT commented on packages/client/src/Core/ValidateForm.tsx
> +  if (!/^[A-ZА-Я][a-zA-Zа-яА-Я\-]*$/.test(values.first_name)) {
Почему тут `snake_case`? Внутренняя договоренность? Почему не используется стандартный для js `camelCase`?

2022-11-30 10:19 UTC, EzhikTT requested changes

2022-11-30 10:19 UTC, EzhikTT commented on packages/client/src/Core/ValidateForm.tsx
> +  if (!/^[A-ZА-Я][a-zA-Zа-яА-Я\-]*$/.test(values.first_name)) {
Почему тут `snake_case`? Внутренняя договоренность? Почему не используется стандартный для js `camelCase`?

2022-11-30 10:19 UTC, EzhikTT commented on packages/client/src/hooks/useForm.tsx
> +export const useForm = (callback: any, validate: any) => {
Почему здесь `any`? Например, `callback` может быть не функцией?

2022-11-30 13:26 UTC, evorobyevaa commented
Исправила замечания

2022-11-30 18:50 UTC, Andrey-A-A approved these changes
Замечаний нет

2022-12-03 10:11 UTC, EzhikTT approved these changes
Все ок

2022-12-03 10:29 UTC, merged