task-27 - add error boundart, task-1 - add rules
wordrunners/bumble pull request #6
Opened 2022-11-30 12:50 UTC by kvitkina

Добавлен Error Boundary

2022-11-30 13:14 UTC, evdoshchenko approved these changes

2022-11-30 13:29 UTC, evorobyevaa approved these changes

2022-12-03 10:11 UTC, EzhikTT commented on packages/client/src/Core/ErrorBoundary.tsx
> +    errorInfo: ErrorInfo | null;
Мб было лучше сделать его опциональным? `errorInfo?: ErrorInfo`

2022-12-03 10:15 UTC, EzhikTT requested changes

2022-12-03 10:15 UTC, EzhikTT commented on packages/client/src/components/Header/Header.tsx
>  export const Header = ():JSX.Element => {
А почему у этого элемента нет указания типа, а у остальных есть?

2022-12-03 10:15 UTC, EzhikTT commented on packages/client/src/Core/ErrorBoundary.tsx
> +export class ErrorBoundary extends Component<Props, State> {
Почему здесь классовый компонент?

2022-12-03 12:40 UTC, kvitkina commented on packages/client/src/Core/ErrorBoundary.tsx
> +export class ErrorBoundary extends Component<Props, State> {
Судя по документации, предохранителями могут быть только классовые компоненты. ![Снимок экрана 2022-12-03 в 15 38 49](https://user-images.githubusercontent.com/63880873/205441345-8c5944e0-aa53-4fcb-86a6-ba78afd05089.png)

2022-12-03 12:41 UTC, kvitkina commented on packages/client/src/components/Header/Header.tsx
>  export const Header = ():JSX.Element => {
У него пока нет пропсов

2022-12-03 12:51 UTC, kvitkina commented on packages/client/src/Core/ErrorBoundary.tsx
> +    errorInfo: ErrorInfo | null;
Сделала опциональным

2022-12-03 20:48 UTC, merged