Task 21 компонент аватар
wordrunners/bumble pull request #7
Opened 2022-11-30 19:49 UTC by Andrey-A-A

### Какую задачу решаем
Создан компонент или раздел с аватаркой, также внесены изменения в работу API в файле avatarApi и в файле apiRequest

### Скриншоты/видяшка (если есть)
![image](https://user-images.githubusercontent.com/76514999/204893603-27ac23fd-732f-4fa6-91f7-dad28e4ee2fd.png)

### TBD (если есть)

2022-11-30 23:08 UTC, evdoshchenko approved these changes

2022-12-01 06:23 UTC, kvitkina approved these changes

2022-12-01 08:41 UTC, evorobyevaa approved these changes

2022-12-03 10:18 UTC, EzhikTT commented on packages/client/src/Core/apiRequest.ts
> +    return sleep().then(() =>
Почему промисы, а не `async/await`?

2022-12-03 10:22 UTC, EzhikTT requested changes

2022-12-03 10:22 UTC, EzhikTT commented on packages/client/src/components/Avatar/Avatar.tsx
> +import avatar from '../../assets/images/avatar.png'
А почему здесь пути не через `@`?

2022-12-03 10:22 UTC, EzhikTT commented on packages/client/src/Core/apiRequest.ts
> +          return isJson ? response.json() : null
Мб лучше, если не `json`, то выбрасывать исключение?

2022-12-03 13:24 UTC, Andrey-A-A commented on packages/client/src/Core/apiRequest.ts
> +    return sleep().then(() =>
Через .then привычнее. Могу я оставить так?

2022-12-03 13:35 UTC, Andrey-A-A commented on packages/client/src/components/Avatar/Avatar.tsx
> +import avatar from '../../assets/images/avatar.png'
пути в импортах поправил

2022-12-03 13:36 UTC, Andrey-A-A commented on packages/client/src/Core/apiRequest.ts
> +          return isJson ? response.json() : null
поправил

2022-12-06 13:54 UTC, EzhikTT commented on packages/client/src/Core/apiRequest.ts
> +    return sleep().then(() =>
Да, окей, это не критично

2022-12-06 13:55 UTC, EzhikTT approved these changes
Хорошо

2022-12-06 20:24 UTC, merged