Task 18 profile
wordrunners/bumble pull request #9
Opened 2022-12-02 18:56 UTC by Andrey-A-A

### Какую задачу решаем
Task 18 Заготовка страницы профиля
Task  3 Профиль
Подготовил страницу profilePage в которую также подгружается компонент для замены аватарки.
Чтобы получать данные пользователя для страниц profilePage и changePasswordPage использовал React.createContext.
Данные пользователя хранятся в файле Core/AppContext.ts
На стартовой странице пока нет ссылки на страницу профиля - поэтому посмотреть её можно по адресу /profile

### Скриншоты/видяшка (если есть)
![image](https://user-images.githubusercontent.com/76514999/205363879-20e10fc9-e132-4871-a36c-6d2434fbed64.png)

### TBD (если есть)

2022-12-02 21:14 UTC, evdoshchenko approved these changes

2022-12-03 10:35 UTC, EzhikTT requested changes

2022-12-03 10:35 UTC, EzhikTT commented on packages/client/src/utils/apiHasError.ts
> +export function hasError(response: any): response is APIError {
Почему здесь сразу не указать тип переменной в параметрах? И указать возвращаемый тип как обычный тип. 
Так же почему, при возврате значения, не создается новый объект?

2022-12-03 10:35 UTC, EzhikTT commented on packages/client/src/pages/changePasswordPage/changePasswordPage.tsx
> +  const oldPasswordHandler = (e: any) => {
Это в прошлом ПРе помечено

2022-12-03 10:35 UTC, EzhikTT commented on packages/client/src/components/InputPassword/InputPassword.tsx
> +const InputPassword: FC<InputProps> = ({
Это в прошлом ПРе помечено

2022-12-03 10:35 UTC, EzhikTT commented on packages/client/src/App.tsx
> +  // useEffect(() => {
Это в прошлом ПРе помечено

2022-12-03 20:46 UTC, Andrey-A-A commented on packages/client/src/utils/apiHasError.ts
> +export function hasError(response: any): response is APIError {
Я не могу сказать, какой конкретный тип переменной будет в разных местах вызова этой  функции.
 Например в API смены пароля сюда будет передана переменная содержащая или ничего или APIError, а в API изменения аватарки переменная типа AvatarResponseData, который описан в api/types.ts,
или APIError.

Что касается второй части вопроса, то такой вариант нам был предложен наставником из предыдущего модуля, и мне он показался достаточно красивым. Насколько я понял, вы предлагаете примерно следущий вариант решения:

```
export function hasError(response: any): string {
  return response?.reason
}
```

Правильно ли я Вас понял?

2022-12-06 14:01 UTC, EzhikTT commented on packages/client/src/utils/apiHasError.ts
> +export function hasError(response: any): response is APIError {
Почти да) Я имел в виду немного другое:
```
type Response = SomeResponceType1 | SomeResponceType2 | SomeResponceType3
export function hasError(response: Response): APIError {
  return response?.reason
}
```
Второй вопрос ок - не так понял

2022-12-06 14:01 UTC, EzhikTT approved these changes
Кроме коммента все ок, ничего критического

2022-12-06 21:10 UTC, merged